bot:
  id: '----'
  sd: '----'
  ems: ''
api:
  base_url: 'riga.kdmid.ru'
  full_path_url: 'default'
logging:
  path: '${file(./Logger/session.txt):PATH}'
  image_path: '----'
  image_ml_path: './Learning Gifs'
